### PR TITLE
Translations and refactoring

### PR DESCRIPTION
**Pull request by mprenditore**
Hello,

I would like to thank everyone that worked on this project.
I had some spare time and decided to play with this app, mostly for experimenting with the graphs.
While seeing the code I started to implement some features like a translation class to make easier for everyone that wanted to add support to multiple languages.
Then I've moved all the functions present in utilities inside a custom class.
I've also found that the csv was loaded only at the start of the application, so to load the new data a restart was needed (or at least this is what I've got), so I've implemented the `get_data()` into the new class that will download the file every time it's initialized, but I've also added the cache to 60s so every minute it's downloaded again so we have updated data as soon as are out.

Let me know what do you think.

Stay safe!

### CODE REVIEW

**Comment by tommasobonomo** [comment]
Hi :) Thank you very much for the kind words and your willingness to get involved!

I had a look at your pull request, the idea is great as the current way of managing languages could surely be improved. The main problem here is the data-flow of Streamlit. As you can read [here](https://docs.streamlit.io/main_concepts.html#data-flow), Streamlit has a particular way of managing the data-flow. I quote: "[...] any time something must be updated on the screen, Streamlit just reruns your entire Python script from top to bottom."

This is why the data fetching method `get_data()` does not need a restart to get new data: it simply collects the most recent `.csv` from the repository of the Protezione Civile everytime something is updated on the screen. This can be definitely managed better, but it helps with having the app always updated to the latest data.

To be clear, the "state" of the app is erased and re-populated everytime something changes. So with class instances, they would be re-instanced everytime. This adds significant overhead when adding regions for example in the widget.

So I can't really accept your pull request. Thank you very much for submitting it, and feel free to ask me anything :)

**Comment by mprenditore** [comment]
Thank you for your reply and the explanation about how Streamlit works.
I agree with you that due to the way ST works having the `get_data()` in the main script is enough, I've modified my branch to instantiate the object in the main script, and I got a bit more performances, not so much but a bit.
But while doing those tests, I also measured the elaboration time for the whole main script on different operations, both on your latest master branch and on mine.

image

As you can see, using classes, the performances have an average increased performance of around 700%, that means 7 times faster.

I hope you will reopen this PR and evaluate it again.

Thanks for you time into developing that.

EDIT:
I run this test on my laptop in powersave mode (4core/8thread 2.6GHz) with a 20Mbps internet connection, so probably the gain on higher specs is lower, but this way the have a better picture of the actual performance improvements in case of higher load on server.

**Comment by mprenditore** [comment]
Here's the comparison with timings on High Performance mode on the CPU (6core/12threads 4 GHz)
image

**Comment by tommasobonomo** [comment]
You are right, the performance definitely improves. I can replicate your gains. But at the moment performance is not a priority for me, as it is perfectly usable as it is. 

At the moment, I want to prioritise adding new features and merging your PR would take away a lot of time to integrate everything. So I will not be doing it at the time. Thank you anyway for your interest, and feel free to fork this project and make whatever changes you may want!

PS: there are some errors in your PR as well, like path definitions in the `translate.py` file (they should start with `src/`) and a lot of stylistic differences

**Pull request closed without merging**
